---
stages:
  - lint
  - build
  # TODO: push to local registry

services:
  - docker:dind

docker_lint:
  stage: lint
  image: lukasmartinelli/hadolint
  script:
    - hadolint --ignore DL3008 Dockerfile

docker_build:
  stage: build
  image: docker:latest
  script:
    - bin/build-docker
