sudo: required

services:
  - docker

install:
  - gem install bundle
  - bundle install

before_script:
  - docker run --rm -i lukasmartinelli/hadolint < Dockerfile
  - docker build -t ansible .

script:
  - rake spec

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" || "$TRAVIS_BRANCH" != "master" ]]; then exit 0; fi
  - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
  - docker tag ansible hamroctopus/ansible:latest
  - docker push hamroctopus/ansible:latest

env:
  global:
  - secure: AQkpGOMJbbT+MAM0D+Whmz6vuWARaIaZd314DrjV7ClB1FiG+Q4p0Nz6NOiIB1tpgO8fg/Urorv5HC37DFVY7N2xHJutuZtE8jnDADljD8zNG+KbtBfXv1CZJ6GqmFwhWEnybFa5BgK/GyfV+LIs97EOQvDsJr7K8ofoOFdLsN9qBi18SBWNI8pMFB6cc2cdRVMj3nrebZgRCJUYEPRLPDNz2krzgUkvvBIuIO7LKF9r5L6IV2BO2ki5PxRsBh3tsLRbVxkikwDML+v5u0wAuZV8PSl0LwKPk59mPbi2NKTRQKhT0K32nka2Wx3MBZZ2EC0wnPVplgLnO+1Wm+tPPEogrlZospD6jSuYhZ7c8FuaX/bXPR/fYXfiHtHi0MbfyCAvMJjlLKoiK72quq5Vdm3t6BK0Jb6ar3Dd/Fcmlmp/VV9Vncuqz5Bti3Fo2cL3Aj58DfJbewgIep8MC+l1dt7+8bb8T9Lei8k2djmaSFyqsa2CSIws8Mo1to/rmoKW/ZhLfX5cW9Y7k+1jxwTFH0FVjzwIr6vGVZDvR4eV4X3Stb5JbC3uqknWQNODMhs41Lih4tFa0V2jEq3p7+hZHzgMG9sNipygVBZnVOzjQH7GP6WjHRNjqh4blazmM2Qs2mVcOKYIAS3oaOCVvaxBHEe4DOBG2oludckZWjiJC6k=
  - secure: uvNZQb1HDZYLD6f1lvNPVyfyrK8mh2l2XsbDuigjN7FCwIZ1CHL9e2Cs2OXQZDmqO2MjCIoN6+t+fXlelcUgaP6yfTS+/zdFD5dEryvlbJV7Q0/u3qKneswhbhPWaohO3KpiyNauyHrILuP0uBK4Yr3xvZHJwU3DUF7HXv6DJw0PFXu1Ko7VGJtXqMmqpFVrBH7IoSpKxLdJp81+KwPg2vbI+C0JrOxFUgMpqx8CT4RP5pL4/9pGkd/d0ECoQzjvWB5RhJIMUbZqi59D14BYcnBO1lcJm8sUt9nj/e/zYSbI54D52m8yC1bOTXzx4vB7d8rNBMgv8uN9HSxlm8Iq3sLM6bYULvAoQ4FpfUflAoR2Kq1DkAxITBp1rqhU9nap3HQjdexzLVpp7i7mAbNCK3v8+rLyDCfndZIn6C6ExeBJgvV6UjI0rFk3oNHiEVj1MgbZ1bE0P21h19ssxQ1aEug2IIO0CcPG50j3DJ4rbVrsn9SB/U5rU39LAKGNSatSXrACsd+Lc9LzDZla5YjSp9l6gNQOzbS0CaabKBhLDhAlpyzTIMAno+Pq09VRDUSqy6aLLHe3vAUY358fEgWZXk/4FpUVCvQ44CNnt3NKabSaTd8xkNwHTL4lWJaZIii8ySwI0nPummZcTBHQu3+PTeEk+CrN7s4HrxtejSrIPCM=
